cmps-383-p1g2/Phase1/Models/Project.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.ComponentModel.DataAnnotations;

namespace Phase1.Models
{
    public class Project
    {
        [Key]
        [Required]
        public int ID { get; set; }
        [Required]
        public String Name { get; set; }
        
        public User AssignedTo { get; set; } //Needs to be dropdown list
        //public virtual IList<User> AssignedTo { get; set; }
        public int UserId { get; set; }
        [Required]
        public string RepositoryLocation { get; set; } // NEEDS TO BE TEXT BOX
    }
}

cmps-383-p1g2/Phase1/Controllers/InteriorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Phase1.Controllers
{
    public class InteriorController : Controller
    {
        //
        // GET: /Interior/

        public ActionResult Index()
        {
            return View();
        }

    }
}

cmps-383-p1g2/Phase1/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Phase1.Models;

namespace Phase1.Controllers
{
    public class ProjectController : Controller
    {
        private DataContext db = new DataContext();

        //
        // GET: /Project/

        public ActionResult Index()
        {
            return View(db.Projects.ToList());
        }

        //
        // GET: /Project/Details/5

        public ActionResult Details(int id = 0)
        {
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        //
        // GET: /Project/Create

        public ActionResult Create()
        {
            ViewBag.UserId = new SelectList(db.Users, "ID", "Name");
            return View();
        }

        //
        // POST: /Project/Create
        
        [HttpPost]
        public ActionResult Create(Project project)
        {
            if (project.UserId != null) { project.AssignedTo = db.Users.Find(project.UserId); }
            if (ModelState.IsValid)
            {

                db.Projects.Add(project);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserId = new SelectList(db.Users, "ID", "Name", project.UserId);
            return View(project);
        }

        //
        // GET: /Project/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserId = new SelectList(db.Users, "ID", "Name", project.UserId);
            return View(project);
        }

        //
        // POST: /Project/Edit/5

        [HttpPost]
        public ActionResult Edit(Project project)
        {
            if (ModelState.IsValid)
            {
                db.Entry(project).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserId = new SelectList(db.Users, "ID", "Name", project.UserId);
            return View(project);
        }

        //
        // GET: /Project/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        //
        // POST: /Project/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Project project = db.Projects.Find(id);
            db.Projects.Remove(project);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

cmps-383-p1g2/Phase1/Views/Project/Create.cshtml
@model Phase1.Models.Project

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Project</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.AssignedTo)
        </div>
        <div class="editor-field">
            @Html.DropDownList("UserId", String.Empty)
            @Html.ValidationMessageFor(model => model.UserId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.RepositoryLocation)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.RepositoryLocation)
            @Html.ValidationMessageFor(model => model.RepositoryLocation)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

cmps-383-p1g2/Phase1/Views/Project/Delete.cshtml
@model Phase1.Models.Project

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Project</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.AssignedTo)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.AssignedTo)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.RepositoryLocation)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.RepositoryLocation)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

cmps-383-p1g2/Phase1/Views/Project/Details.cshtml
@model Phase1.Models.Project

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Project</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.AssignedTo)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.AssignedTo)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.RepositoryLocation)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.RepositoryLocation)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

cmps-383-p1g2/Phase1/Views/Project/Edit.cshtml
@model Phase1.Models.Project

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Project</legend>

        @Html.HiddenFor(model => model.ID)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserId)
        </div>
        <div class="editor-field">
            @Html.DropDownList("UserId", String.Empty)
            @Html.ValidationMessageFor(model => model.UserId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.RepositoryLocation)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.RepositoryLocation)
            @Html.ValidationMessageFor(model => model.RepositoryLocation)
        </div>

        <p>
            <input type="submit" value="Submit" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

cmps-383-p1g2/Phase1/Views/Project/Index.cshtml
@model IEnumerable<Phase1.Models.Project>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RepositoryLocation)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AssignedTo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RepositoryLocation)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
           
    </tr>
}
             @Html.ActionLink("Home", "Index", "Interior")
</table>